### ISSUE TITLE
plot() issue

### ISSUE THREAD

**Issue by dliao1** [julia-wrobel/mxfda#14]
Hi!

I'm encountering an issue where I'm using run_fpca and trying to plot the results.

Here is the code I used:
```{r}
mxFDAobject_K_aaces <- run_fpca(mxFDAobject_K_aaces, 
                        metric = "uni k", 
                        r = "r", 
                        value = "fundiff",
                        pve = .99)

summary(mxFDAobject_K_aaces)

K_fpca = extract_fpca_object(mxFDAobject_K_aaces,
                             what = "uni k fpca")

library(refund.shiny)
plot_shiny(K_fpca)

p1 = plot(mxFDAobject_K_aaces, what = 'uni k fpca', pc_choice = 1)
p2 = plot(mxFDAobject_K_aaces, what = 'uni k fpca', pc_choice = 2)

ggarrange(p1, p2, nrow = 1, ncol = 2)

summary(mxFDAobject_K_aaces)
```

The error I get is as follows: 
```{r}
> p1 = plot(mxFDAobject_K_aaces, what = 'uni k fpca', pc_choice = 1)
Error in seq.default(obj$index_range[1], obj$index_range[2], length.out = length(obj$mu)) : 
  'from' must be a finite number
```

Plotting seems to work fine using refund.shiny on the extracted FPCA object, but errors out as soon as I try to use the plot() function.  I'm not sure if it's the syntax I'm using or something else - any guidance would be greatly appreciated!

**Comment by ACSoupir** [comment]
Creating a radii range slot depended on the `r` in the output of calculating univariate/bivariate metrics to not have missing values. 

https://github.com/julia-wrobel/mxfda/blob/34a94163b82f508bd84387b9da8df82ff7046a94/R/run_fpca.R#L80 

Has been updated to reflect changes to https://github.com/julia-wrobel/mxfda/commit/e59f28b8de0e699e4446a2cc7528b6b9c69fa52c increment to v0.2.1-1
